import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local';
import Footer from "../components/Footer";
import Header from "../components/Header";
import Tutorials from "../sections/tutorials";
import "./globals.css";

const ppmori = localFont({ src: './../assets/fonts/PPMori-SemiBold.otf', variable: "--font-ppmori-semibold", })
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${ppmori.variable}`}>
        <div className="bg-[url('../assets/images/img_bg_mobile.png')] lg:bg-[url('../assets/images/img_bg_desktop.png')] bg-cover bg-no-repeat">
          <Header />
          {children}
          <Tutorials />
          <Footer />
        </div>
      </body>
    </html>
  );
}
